const faker = require("faker");

function generateIngredient() {
  const ingredient = {
    ingredientName: faker.random.arrayElement([
      "Pomme de terre",
      "Carotte",
      "Tomate",
      "Oignon",
      "Poivron",
      "Courgette",
      "Concombre",
      "Aubergine",
      "Brocoli",
      "Chou-fleur",
      "Épinard",
      "Laitue",
      "Radis",
      "Poireau",
      "Céleri",
      "Navet",
      "Betterave",
      "Panais",
      "Haricot vert",
      "Petit pois",
      "Maïs",
      "Asperge",
      "Artichaut",
      "Champignon",
      "Courge",
      "Potiron",
      "Patate douce",
      "Chou-rave",
      "Rutabaga",
      "Endive",
      "Fenouil",
      "Pois chiche",
      "Lentille",
      "Haricot pinto",
      "Haricot noir",
      "Haricot rouge",
      "Haricot blanc",
      "Haricot mungo",
      "Haricot azuki",
      "Haricot borlotti",
      "Haricot garbanzo",
      "Haricot flageolet",
      "Haricot lima",
      "Haricot navy",
      "Haricot rouge kidney",
      "Chou vert",
      "Chou rouge",
      "Haricot cassé",
      "Pois gourmand",
      "Pomme",
      "Banane",
      "Orange",
      "Fraise",
      "Raisin",
      "Citron",
      "Kiwi",
      "Poire",
      "Cerise",
      "Abricot",
      "Ananas",
      "Mangue",
      "Pamplemousse",
      "Pêche",
      "Framboise",
      "Myrtille",
      "Pastèque",
      "Prune",
      "Nectarine",
      "Groseille",
      "Cassis",
      "Grenade",
      "Pomme verte",
      "Banane plantain",
      "Citron vert",
      "Kaki",
      "Noix de coco",
      "Papaye",
      "Figue",
      "Pomme d api",
      "Goyave",
      "Mûre",
      "Fruit de la passion",
      "Carambole",
      "Litchi",
      "Grenade",
      "Datte",
      "Cantaloup",
      "Noix",
      "Anone",
      "Pitaya",
      "Feijoa",
      "Groseille à maquereau",
      "Mandarine",
      "Nashi",
      "Rhubarbe",
      "Goji",
      "Cerise acide",
      "Pomelo",
      "Riz",
      "Pâtes",
      "Pommes de terre",
      "Blé",
      "Maïs",
      "Orge",
      "Avoine",
      "Quinoa",
      "Boulgour",
      "Couscous",
      "Millet",
      "Sarrasin",
      "Farro",
      "Riz sauvage",
      "Patate douce",
      "Tapioca",
      "Manioc",
      "Châtaigne",
      "Pain complet",
      "Pain de seigle",
      "Pain de blé entier",
      "Pain aux noix",
      "Pain aux céréales",
      "Pain aux graines de lin",
      "Pain aux graines de tournesol",
      "Baguette de pain",
      "Chapati",
      "Naan",
      "Tortilla",
      "Pain pita",
      "Biscottes",
      "Riz gluant",
      "Polenta",
      "Gnocchis",
      "Cassave",
      "Epeautre",
      "Ravioli",
      "Pain de maïs",
      "Fettuccine",
      "Spaghetti",
      "Lasagnes",
      "Macaroni",
      "Rigatoni",
      "Tagliatelles",
      "Fusilli",
      "Linguine",
      "Vermicelles",
      "Campanelle",
      "Ziti",
      "Penne",
      "Cheddar",
      "Mozzarella",
      "Carbonara",
      "Parmesan",
      "Brie",
      "Camembert",
      "Gouda",
      "Feta",
      "Roquefort",
      "Gruyère",
      "Emmental",
      "Fromage de chèvre",
      "Comté",
      "Ricotta",
      "Fromage de brebis",
      "Blue Stilton",
      "Gorgonzola",
      "Munster",
      "Colby",
      "Havarti",
      "Limburger",
      "Bleu d Auvergne",
      "Provolone",
      "Cottage cheese",
      "Monterey Jack",
      "Pepper Jack",
      "Mimolette",
      "Queso fresco",
      "Queso blanco",
      "Queso de bola",
      "Queso de cabra",
      "Queso de oveja",
      "Queso de vaca",
      "Queso de cabrales",
      "Queso de Manchego",
      "Queso de Roquefort",
      "Queso de Tetilla",
      "Queso fundido",
      "Queso Gouda ahumado",
      "Queso Panela",
      "Queso Pecorino",
      "Queso Roquefort",
      "Queso suizo",
      "Queso de cabra con hierbas",
      "Queso de cabra con pimienta",
      "Queso de cabra con arándanos",
      "Queso de cabra con ajo y finas hierbas",
      "Queso de cabra con nueces",
      "Queso de cabra con romero",
      "Poulet",
      "Bœuf",
      "Porc",
      "Agneau",
      "Dinde",
      "Canard",
      "Jambon",
      "Salami",
      "Chorizo",
      "Saucisson",
      "Bacon",
      "Côte de porc",
      "Steak",
      "Côtelette d agneau",
      "Poulet rôti",
      "Saucisse",
      "Filet mignon",
      "Côtes levées",
      "Viande hachée",
      "Andouille",
      "Saucisse de Francfort",
      "Pastrami",
      "Pancetta",
      "Saucisse italienne",
      "Rôti de bœuf",
      "Saucisse merguez",
      "Saucisse de Toulouse",
      "Cervelas",
      "Saucisse bratwurst",
      "Saucisse de Vienne",
      "Saucisse de porc à l ail",
      "Lardons",
      "Viande de veau",
      "Boudin noir",
      "Boudin blanc",
      "Champignons de Paris farcis",
      "Lomo",
      "Filet de canard",
      "Rosbif",
      "Pâté de foie gras",
      "Saucisse de chorizo sec",
      "Viande de kangourou",
      "Saucisse de canard",
      "Rôti de dinde",
      "Steak haché",
      "Magret de canard",
      "Saucisse de porc fumée",
      "Viande de gibier",
      "Sel",
      "Poivre",
      "Ail en poudre",
      "Oignon en poudre",
      "Cumin",
      "Paprika",
      "Curry en poudre",
      "Gingembre en poudre",
      "Cannelle",
      "Noix de muscade",
      "Clou de girofle",
      "Piment de Cayenne",
      "Coriandre en poudre",
      "Cumin moulu",
      "Sauge",
      "Thym",
      "Romarin",
      "Origan",
      "Basilic",
      "Ciboulette",
      "Persil",
      "Aneth",
      "Coriandre fraîche",
      "Menthe",
      "Curry en pâte",
      "Pâte de tomate",
      "Ketchup",
      "Moutarde",
      "Mayonnaise",
      "Sauce soja",
      "Sauce teriyaki",
      "Sauce Worcestershire",
      "Vinaigre balsamique",
      "Vinaigre de vin rouge",
      "Vinaigre de cidre",
      "Huile dolive",
      "Huile de sésame",
      "Huile de noix",
      "Huile de maïs",
      "Huile de tournesol",
      "Vinaigrette",
      "Sauce barbecue",
      "Sauce chili",
      "Sauce hoisin",
      "Sauce sriracha",
      "Sauce ranch",
      "Sauce tartare",
      "Sauce à lail",
      "Sauce au fromage bleu",
      "Œuf",
      "Lait",
      "Crème",
      "Beurre",
      "Sucre",
      "Farine",
      "Levure chimique",
      "Extrait de vanille",
      "Chocolat",
      "Cacao en poudre",
      "Noix de coco râpée",
      "Noix",
      "Amandes",
      "Noisettes",
      "Pistaches",
      "Miel",
      "Sirop dérable",
      "Pain de mie",
      "Pain grillé",
      "Cornflakes",
      "Flocons davoine",
      "Muesli",
      "Granola",
      "Noix de Grenoble",
      "Pépites de chocolat",
      "Cassonade",
      "Sucre glace",
      "Sucre brun",
      "Sucre roux",
      "Sirop de maïs",
      "Gelée de fruits",
      "Compote de pommes",
      "Confiture",
      "Crème fouettée",
      "Pâte feuilletée",
      "Pâte brisée",
      "Pâte à pizza",
      "Pâte à tarte",
      "Sauce tomate",
      "Bouillon de poulet",
      "Bouillon de légumes",
      "Vinaigre blanc",
      "Vinaigre de vin blanc",
      "Levure de bière",
      "Levure nutritionnelle",
      "Poudre damande",
      "Gélatine",
      "Ail frais",
      "Échalote",
      "Champignons",
      "Eau de rose",
    ]),
  };
  return ingredient;
}
module.exports = generateIngredient;
