const faker = require("faker");

function generateRecipe() {
  const recipes = {
    recipeName: faker.random.arrayElement([
      "Coq au Vin (France)",
      "Bœuf Bourguignon (France)",
      "Ratatouille (France)",
      "Quiche Lorraine (France)",
      "Cassoulet (France)",
      "Bouillabaisse (France)",
      "Crème Brûlée (France)",
      "Tarte Tatin (France)",
      "Confit de Canard (France)",
      "Salade Niçoise (France)",
      "Soupe à l Oignon (France)",
      "Escargots de Bourgogne (France)",
      "Gratin Dauphinois (France)",
      "Blanquette de Veau (France)",
      "Pissaladière (France)",
      "Pot-au-Feu (France)",
      "Boucheé à la Reine (France)",
      "Tartiflette (France)",
      "Poulet Basquaise (France)",
      "Boudin Noir aux Pommes (France)",
      "Hachis Parmentier (France)",
      "Poulet Fricassée (France)",
      "Quenelles de Brochet (France)",
      "Crêpes Suzette (France)",
      "Baba au Rhum (France)",
      "Salade Lyonnaise (France)",
      "Choucroute Garnie (France)",
      "Piperade (France)",
      "Tarte Flambée (France)",
      "Navarin d Agneau (France)",
      "Daube Provençale (France)",
      "Chateaubriand (France)",
      "Fondue Savoyarde (France)",
      "Rouille (France)",
      "Sole Meunière (France)",
      "Cassoulet Toulousain (France)",
      "Blanc-Manger (France)",
      "Poulet Marengo (France)",
      "Quiche Alsacienne (France)",
      "Potée Auvergnate (France)",
      "Poulet Vallée d Auge (France)",
      "Chateaubriand Béarnaise (France)",
      "Oeufs en Meurette (France)",
      "Salade Frisée aux Lardons (France)",
      "Rognons de Veau à la Moutarde (France)",
      "Matelote d Anguille (France)",
      "Crème Normande (France)",
      "Poulet Chasseur (France)",
      "Ratatouille Niçoise (France)",
      "Paella (Espagnol)",
      "Tortilla Española (Espagnol)",
      "Gazpacho (Espagnol)",
      "Pulpo a la Gallega (Espagnol)",
      "Churros con Chocolate (Espagnol)",
      "Fabada Asturiana (Espagnol)",
      "Croquetas (Espagnol)",
      "Salmorejo (Espagnol)",
      "Arroz con Leche (Espagnol)",
      "Pinchos (Espagnol)",
      "Albóndigas en Salsa (Espagnol)",
      "Cocido Madrileño (Espagnol)",
      "Bacalao a la Vizcaína (Espagnol)",
      "Pisto (Espagnol)",
      "Sangria (Espagnol)",
      "Calamares a la Romana (Espagnol)",
      "Ensalada Mixta (Espagnol)",
      "Gambas al Ajillo (Espagnol)",
      "Tarta de Santiago (Espagnol)",
      "Pulpo a Feira (Espagnol)",
      "Tarta de Queso (Espagnol)",
      "Empanadas (Espagnol)",
      "Patatas Bravas (Espagnol)",
      "Sopa de Ajo (Espagnol)",
      "Polvorones (Espagnol)",
      "Cochinillo Asado (Espagnol)",
      "Crema Catalana (Espagnol)",
      "Horchata (Espagnol)",
      "Rabo de Toro (Espagnol)",
      "Tarta de Manzana (Espagnol)",
      "Berenjenas con Miel (Espagnol)",
      "Marmitako (Espagnol)",
      "Crema de Almendras (Espagnol)",
      "Tarta de Tres Leches (Espagnol)",
      "Caracoles a la Andaluza (Espagnol)",
      "Pimientos de Padrón (Espagnol)",
      "Ropa Vieja (Espagnol)",
      "Tarta de Chocolate (Espagnol)",
      "Sardinas a la Plancha (Espagnol)",
      "Buñuelos de Viento (Espagnol)",
      "Arroz a la Cubana (Espagnol)",
      "Pimientos Rellenos (Espagnol)",
      "Fideuà (Espagnol)",
      "Cazuela de Mariscos (Espagnol)",
      "Huevos Rotos (Espagnol)",
      "Pasta de Te (Espagnol)",
      "Chicharrones (Espagnol)",
      "Tarta de Nuez (Espagnol)",
      "Cordero Lechal Asado (Espagnol)",
      "Pizza Margherita (Italie)",
      "Pâtes à la Carbonara (Italie)",
      "Lasagnes (Italie)",
      "Tiramisu (Italie)",
      "Risotto aux Champignons (Italie)",
      "Pesto Genovese (Italie)",
      "Spaghetti Bolognese (Italie)",
      "Cannoli Siciliani (Italie)",
      "Osso Buco (Italie)",
      "Gnocchis à la Sauce Tomate (Italie)",
      "Raviolis (Italie)",
      "Minestrone (Italie)",
      "Orecchiette aux Brocolis (Italie)",
      "Panna Cotta (Italie)",
      "Bruschetta (Italie)",
      "Parmigiana d Aubergines (Italie)",
      "Cacio e Pepe (Italie)",
      "Tortellini (Italie)",
      "Focaccia (Italie)",
      "Arancini (Italie)",
      "Poulet Parmesan (Italie)",
      "Caprese (Italie)",
      "Panettone (Italie)",
      "Polenta (Italie)",
      "Tartufo (Italie)",
      "Zuppa Toscana (Italie)",
      "Baccalà alla Vicentina (Italie)",
      "Cioppino (Italie)",
      "Calzone (Italie)",
      "Pâtes à l Arrabbiata (Italie)",
      "Frittata (Italie)",
      "Pizzelle (Italie)",
      "Gâteau à la Ricotta (Italie)",
      "Pâtes au Beurre et au Parmesan (Italie)",
      "Carpaccio (Italie)",
      "Pâtes à la Vongole (Italie)",
      "Struffoli (Italie)",
      "Braciola (Italie)",
      "Gelato (Italie)",
      "Cannelloni (Italie)",
      "Pâtes au Pistou (Italie)",
      "Zabaione (Italie)",
      "Amaretti (Italie)",
      "Pâtes aux Noix et au Gorgonzola (Italie)",
      "Torta della Nonna (Italie)",
      "Pâtes à l Amatriciana (Italie)",
      "Panna Cotta aux Fruits Rouges (Italie)",
      "Coda alla Vaccinara (Italie)",
      "Risotto au Safran (Italie)",
      "Biscotti (Italie)",
      "Pizzelle (Italie)",
      "Hamburger (USA)",
      "Hot Dog (USA)",
      "Poulet frit (USA)",
      "Côtes levées (USA)",
      "Tarte aux pommes (USA)",
      "Brownies (USA)",
      "Pain de viande (USA)",
      "Beignets (USA)",
      "Biscuits et sauce (USA)",
      "Macaroni au fromage (USA)",
      "Bœuf séché (USA)",
      "Clam Chowder (USA)",
      "Gumbo (USA)",
      "Biscuits au babeurre (USA)",
      "Pain de maïs (USA)",
      "Pancakes (USA)",
      "Tacos (USA)",
      "Burritos (USA)",
      "Barbecue ribs (USA)",
      "Bœuf haché (USA)",
      "Chili (USA)",
      "Poulet rôti (USA)",
      "Cornbread (USA)",
      "Fried chicken (USA)",
      "Cobb salad (USA)",
      "Jambalaya (USA)",
      "Sloppy Joes (USA)",
      "Potato salad (USA)",
      "Chocolate chip cookies (USA)",
      "Peanut butter and jelly sandwich (USA)",
      "Philly cheesesteak (USA)",
      "Buffalo wings (USA)",
      "Apple pie (USA)",
      "Pumpkin pie (USA)",
      "Cheesecake (USA)",
      "Red velvet cake (USA)",
      "Key lime pie (USA)",
      "Southern fried chicken (USA)",
      "Pecan pie (USA)",
      "Biscuits and gravy (USA)",
      "Shrimp and grits (USA)",
      "Grits (USA)",
      "Corn dogs (USA)",
      "Tater tots (USA)",
      "Fried catfish (USA)",
      "Hush puppies (USA)",
      "Chicken and waffles (USA)",
      "S mores (USA)",
      "Fried okra (USA)",
      "Sushi (Japon)",
      "Sashimi (Japon)",
      "Maki (Japon)",
      "Tempura (Japon)",
      "Ramen (Japon)",
      "Udon (Japon)",
      "Soba (Japon)",
      "Okonomiyaki (Japon)",
      "Yakitori (Japon)",
      "Tonkatsu (Japon)",
      "Gyoza (Japon)",
      "Takoyaki (Japon)",
      "Nigiri (Japon)",
      "Chirashi (Japon)",
      "Onigiri (Japon)",
      "Yaki Soba (Japon)",
      "Sukiyaki (Japon)",
      "Teriyaki (Japon)",
      "Shabu-Shabu (Japon)",
      "Katsu Don (Japon)",
      "Miso Soup (Japon)",
      "Somen (Japon)",
      "Yuba (Japon)",
      "Nattō (Japon)",
      "Sukiyaki (Japon)",
      "Unagi (Japon)",
      "Yakitori (Japon)",
      "Nabemono (Japon)",
      "Sunomono (Japon)",
      "Chawanmushi (Japon)",
      "Oyakodon (Japon)",
      "Taiyaki (Japon)",
      "Yudofu (Japon)",
      "Kare Raisu (Japon)",
      "Yakisoba (Japon)",
      "Kitsune Udon (Japon)",
      "Oshiruko (Japon)",
      "Gomaae (Japon)",
      "Hōtō (Japon)",
      "Nanakusa-gayu (Japon)",
      "Ozōni (Japon)",
      "Chazuke (Japon)",
      "Zōsui (Japon)",
      "Yōkan (Japon)",
      "Hōtō (Japon)",
      "Shiratama Dango (Japon)",
      "Yatsuhashi (Japon)",
      "Okowa (Japon)",
      "Kara-age (Japon)",
      "Korokke (Japon)",
      "Hiyashi Chuka (Japon)",
      "Pad Thai (Thaï)",
      "Tom Yum Goong (Thaï)",
      "Green Curry (Kaeng Khiao Wan) (Thaï)",
      "Red Curry (Kaeng Phet) (Thaï)",
      "Massaman Curry (Kaeng Matsaman) (Thaï)",
      "Papaya Salad (Som Tum) (Thaï)",
      "Tom Kha Gai (Thaï)",
      "Pad Krapow Moo Saap (Thaï)",
      "Tom Kha Kai (Thaï)",
      "Pineapple Fried Rice (Khao Pad Sapparot) (Thaï)",
      "Thai Fried Chicken (Gai Tod) (Thaï)",
      "Laab (Larb) (Thaï)",
      "Panang Curry (Kaeng Phanaeng) (Thaï)",
      "Green Papaya Salad (Som Tum) (Thaï)",
      "Chicken Satay (Satay Gai) (Thaï)",
      "Sticky Rice with Mango (Khao Niew Mamuang) (Thaï)",
      "Yellow Curry (Kaeng Kari) (Thaï)",
      "Crab Fried Rice (Khao Pad Pu) (Thaï)",
      "Coconut Soup (Tom Kha) (Thaï)",
      "Thai Iced Tea (Thaï)",
      "Thai Beef Salad (Yam Nua) (Thaï)",
      "Pad See Ew (Thaï)",
      "Thai Basil Chicken (Gai Pad Krapow) (Thaï)",
      "Thai Grilled Pork (Moo Ping) (Thaï)",
      "Shrimp Pad Thai (Thaï)",
      "Pork Satay (Satay Moo) (Thaï)",
      "Green Curry Chicken (Gaeng Kiaw Wan Gai) (Thaï)",
      "Spicy Thai Noodles (Pad Kee Mao) (Thaï)",
      "Spicy Basil Eggplant (Pad Makua Yao) (Thaï)",
      "Pad Thai Goong Sod (Thaï)",
      "Thai Red Curry Beef (Kaeng Phet Nuea) (Thaï)",
      "Glass Noodle Salad (Yam Woon Sen) (Thaï)",
      "Cashew Chicken (Gai Pad Med Mamuang) (Thaï)",
      "Tom Yum Chicken (Thaï)",
      "Thai Coconut Cake (Kanom Tuay) (Thaï)",
      "Fried Bananas (Kluay Tod) (Thaï)",
      "Thai Peanut Sauce (Thaï)",
      "Grilled Thai-Style Chicken (Gai Yang) (Thaï)",
      "Pork Green Curry (Kaeng Khiao Wan Moo) (Thaï)",
      "Thai Fish Curry (Kaeng Pla) (Thaï)",
      "Thai Cucumber Salad (Tangy Thai Cucumber Salad) (Thaï)",
      "Pad Thai Gai (Thaï)",
      "Tom Yum Talay (Thaï)",
      "Papaya Salad with Salted Crab (Som Tum Poo) (Thaï)",
      "Thai Pumpkin Curry (Fak Thong Gaeng Phet) (Thaï)",
      "Spicy Thai Red Curry Shrimp (Kaeng Phet Goong) (Thaï)",
      "Thai Red Curry Tofu (Kaeng Phet Tao Hu) (Thaï)",
      "Thai Yellow Curry Chicken (Gaeng Kari Gai) (Thaï)",
      "Thai Pineapple Fried Rice (Khao Pad Sapparot) (Thaï)",
      "Moules-frites (Belgique)",
      "Carbonade flamande (Belgique)",
      "Waterzooi (Belgique)",
      "Boudin noir (Belgique)",
      "Chicons au gratin (Belgique)",
      "Stoemp (Belgique)",
      "Vol-au-vent (Belgique)",
      "Gaufres de Bruxelles (Belgique)",
      "Gaufres de Liège (Belgique)",
      "Speculoos (Belgique)",
      "Boulets à la Liégeoise (Belgique)",
      "Cervelas (Belgique)",
      "Chicons au gratin (Belgique)",
      "Cochon de lait à la broche (Belgique)",
      "Dame blanche (Belgique)",
      "Potjevleesch (Belgique)",
      "Hochepot (Belgique)",
      "Pain à la grecque (Belgique)",
      "Pain de viande (Belgique)",
      "Pistolet (Belgique)",
      "Tomates aux crevettes (Belgique)",
      "Tarte au sucre (Belgique)",
      "Tarte au riz (Belgique)",
      "Carbonnades à la flamande (Belgique)",
      "Anguilles au vert (Belgique)",
      "Blanc-manger (Belgique)",
      "Bouilli (Belgique)",
      "Chicon gratin (Belgique)",
      "Chicons aux lardons (Belgique)",
      "Cougnou (Belgique)",
      "Crêpe à l ail (Belgique)",
      "Crêpe Suzette (Belgique)",
      "Croquette aux crevettes (Belgique)",
      "Fricadelle (Belgique)",
      "Frites (Belgique)",
      "Hareng saur (Belgique)",
      "Lapin à la Kriek (Belgique)",
      "Maton (Belgique)",
      "Pain à la bière (Belgique)",
      "Pain aux raisins (Belgique)",
      "Pain saucisse (Belgique)",
      "Pain viennois (Belgique)",
      "Pain d Anis (Belgique)",
      "Tarte à la bière (Belgique)",
      "Tarte au fromage blanc (Belgique)",
      "Tarte au sucre de Liège (Belgique)",
      "Tarte au sucre de sable (Belgique)",
      "Tarte au sucre perlé (Belgique)",
      "Tarte aux prunes (Belgique)",
      "Raclette (Suisse)",
      "Fondue suisse (Suisse)",
      "Rösti (Suisse)",
      "Tartiflette (Suisse)",
      "Pizzoccheri (Suisse)",
      "Saucisse de porc à l ail (Suisse)",
      "Bircher Müesli (Suisse)",
      "Zürcher Geschnetzeltes (Suisse)",
      "Bâtonnets de fromage (Suisse)",
      "Tête de Moine (Suisse)",
      "Malakoff (Suisse)",
      "Fribourg Fondue (Suisse)",
      "Biberli (Suisse)",
      "Linzer Torte (Suisse)",
      "Eierschwämmli (Suisse)",
      "Cervelas (Suisse)",
      "Quarkkäulchen (Suisse)",
      "Schwarzwälder Kirschtorte (Suisse)",
      "Raisinée (Suisse)",
      "Cholera (Suisse)",
      "Cheese Fritters (Suisse)",
      "Spannferkel (Suisse)",
      "Cuchaule (Suisse)",
      "Zuger Kirschtorte (Suisse)",
      "Tourte aux poireaux (Suisse)",
      "Fleischkäse (Suisse)",
      "Pain de seigle suisse (Suisse)",
      "Poulet yassa (Suisse)",
      "Bündner Nusstorte (Suisse)",
      "Gâteau aux carottes suisse (Suisse)",
      "Apfelküchlein (Suisse)",
      "Saucisson vaudois (Suisse)",
      "Saucisse à rôtir (Suisse)",
      "Riz casimir (Suisse)",
      "Bricelet (Suisse)",
      "Truffes au chocolat suisses (Suisse)",
      "Pains aux noix (Suisse)",
      "Filets de perche meunière (Suisse)",
      "Stollen suisse (Suisse)",
      "Gâteau de Pâques suisse (Suisse)",
      "Pain aux noix suisse (Suisse)",
      "Beurre de noix suisse (Suisse)",
      "Grappa suisse (Suisse)",
      "Zwetschgenkuchen (Suisse)",
      "Pain d épice suisse (Suisse)",
      "Glace à la meringue suisse (Suisse)",
      "Meringue suisse (Suisse)",
      "Chasseur de cerf (Suisse)",
      "Légumes au beurre suisse (Suisse)",
      "Couscous (Maroc)",
      "Tajine (Maroc)",
      "Pastilla (Maroc)",
      "Harira (Maroc)",
      "Méchoui (Maroc)",
      "Mrouzia (Maroc)",
      "Chermoula (Maroc)",
      "Briouat (Maroc)",
      "B stilla (Maroc)",
      "Kefta (Maroc)",
      "Zaalouk (Maroc)",
      "Makrout (Maroc)",
      "Baghrir (Maroc)",
      "Rfissa (Maroc)",
      "Khobz (Maroc)",
      "Chbah Essafra (Tunisie)",
      "Couscous au poisson (Tunisie)",
      "Brik (Tunisie)",
      "Tajine de poisson (Tunisie)",
      "Chorba (Algérie)",
      "Couscous algérien (Algérie)",
      "M hencha (Algérie)",
      "Makrout (Algérie)",
      "Chorba frik (Algérie)",
      "Rechta (Algérie)",
      "Harira (Algérie)",
      "Chakhchoukha (Algérie)",
      "Chakchouka (Tunisie)",
      "Mloukhia (Tunisie)",
      "Ojja (Tunisie)",
      "Makroud (Tunisie)",
      "Khobz Tabouna (Tunisie)",
      "Couscous aux légumes (Tunisie)",
      "Mderbel (Tunisie)",
      "Makbous (Tunisie)",
      "Broudou (Tunisie)",
      "Jelbana (Tunisie)",
      "Tebikha (Tunisie)",
      "Tajine de poulet aux olives (Tunisie)",
      "Brik à l œuf (Tunisie)",
      "Merguez (Tunisie)",
      "Salade Mechouia (Tunisie)",
      "Briq (Tunisie)",
      "Kafteji (Tunisie)",
      "Harira aux boulettes (Tunisie)",
      "Couscous aux sept légumes (Tunisie)",
      "Moutabal (Tunisie)",
      "Bsalu (Tunisie)",
      "Ragoût de mouton aux fèves (Algérie)",
    ]),
    description: faker.lorem.sentences(5, true),
    difficulte: faker.random.number({ min: 0, max: 5}),
  };
  return recipes;
}
module.exports = generateRecipe;
